### ISSUE TITLE
Error when attempting to renew

### ISSUE THREAD

**Issue by nilsjesper** [tiagoamaro/pickpocket-rust#1]
I realize this project may not be in active development but I'm seeing an error which I didn't previously when trying to renew. This happens even when I delete my ~/.pickpocket directory and do the whole re-auth process.

```
~ ➤ pickpocket renew
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0: std::sys_common::backtrace::print
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::continue_panic_fmt
   5: rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::panicking::panic
   8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   9: pickpocket::articles::library::Library::renew
  10: pickpocket::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
```

Unfortunately I don't know Rust worth a damn or I'd try to dig into what's going on. But if it's a simple fix, I've really loved this tool and would love to keep using it.

Thanks for building it!

**Comment by tiagoamaro** [comment]
Will check it out!

> I realize this project may not be in active development...

Think of it as "feature complete". Didn't have anything else to implement, use it in a daily basis and pretty happy with it :smile:

**Comment by tiagoamaro** [comment]
Hi @nilsjesper, I had this error earlier, but now it's working fine.

I found out that Pocket wasn't returning the authorization token, which is being written in the `~/.pickpocket/authorization_token` file, making  unauthorized requests to its API.

The error message wasn't clear at all, as I never added the scenario where one would get a 401 HTTP status and an empty string as a result.

If you follow the `pickpocket oauth` and `pickpocket authorize` process again, it should work now.

**Comment by nilsjesper** [comment]
Hi @tiagoamaro  - I realize I never checked back in on this! Thanks for the heads up and I'm excited to get this working again since it was huge for me!

I was able to install a fresh copy  but now when I try to renew the library, sadly I'm getting a timeout the first time `[Pickpocket] https://getpocket.com/v3/send: timed out` resulting in an empty library file.

Subsequent renews is getting

```
[Pickpocket] Inventory file not found. Creating...
[Pickpocket] Could not retrieve Pocket's data
[Pickpocket] Refreshed library
[Pickpocket] You have 0 read articles
[Pickpocket] You have 0 unread articles
```

I'll see if I can do some debugging too!
